//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDevGrp.OSIntranet.DataAccess.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDevGrp.OSIntranet.DataAccess.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 106.
        /// </summary>
        internal static string EventLogAdresseRepositoryService {
            get {
                return ResourceManager.GetString("EventLogAdresseRepositoryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 108.
        /// </summary>
        internal static string EventLogDbAxRepositoryWatcherId {
            get {
                return ResourceManager.GetString("EventLogDbAxRepositoryWatcherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 107.
        /// </summary>
        internal static string EventLogFinansstyringRepositoryService {
            get {
                return ResourceManager.GetString("EventLogFinansstyringRepositoryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Intranet - Data Access.
        /// </summary>
        internal static string EventLogName {
            get {
                return ResourceManager.GetString("EventLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104.
        /// </summary>
        internal static string EventLogOnContinueExceptionId {
            get {
                return ResourceManager.GetString("EventLogOnContinueExceptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 103.
        /// </summary>
        internal static string EventLogOnPauseExceptionId {
            get {
                return ResourceManager.GetString("EventLogOnPauseExceptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 105.
        /// </summary>
        internal static string EventLogOnShutdownExceptionId {
            get {
                return ResourceManager.GetString("EventLogOnShutdownExceptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101.
        /// </summary>
        internal static string EventLogOnStartExceptionId {
            get {
                return ResourceManager.GetString("EventLogOnStartExceptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102.
        /// </summary>
        internal static string EventLogOnStopExceptionId {
            get {
                return ResourceManager.GetString("EventLogOnStopExceptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSDevGrp.OSIntranet.DataAccess.CustomLog.
        /// </summary>
        internal static string EventLogSource {
            get {
                return ResourceManager.GetString("EventLogSource", resourceCulture);
            }
        }
    }
}
